# 公有仓库
source 'https://github.com/CocoaPods/Specs.git'


platform :ios, '10.0'

install! 'cocoapods', :disable_input_output_paths => true

target 'JKQuickApp-iOS' do
  
  use_frameworks!
    
    pod 'SnapKit', '~> 5.0.1'
 # Json数据解析
  #pod 'SwiftyJSON', '~> 4.0'

  # Json转模型
  #pod 'HandyJSON', '~> 5.0.2'

  
end


# 处理不同模块引用问题
post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
  installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
     end
   end
end

